version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - LANG=C.UTF-8
      - TZ=America/Sao_Paulo
    ports:
      - 3306:3306
    networks:
      - rede-interna
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: ./app
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./app:/home/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - rede-externa
      - rede-interna
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      timeout: 10s
      retries: 5

  nginx:
    build: ./nginx
    ports:
        - 8000:80
        - 8080:80
    depends_on:
      web:
        condition: service_healthy
    networks:
      - rede-externa
    restart: on-failure

networks:
  rede-externa:
    driver: bridge
  rede-interna:
    driver: bridge
    internal: true
