version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - 3306:3306
  web:
    build: ./app
    volumes:
      - ./app:/home/app
    depends_on:
      - mysql

  nginx:
    build: ./nginx
    ports:
        - 8080:80
    depends_on:
        - web