version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - 3306:3306
    networks:
      - rede-interna
  web:
    build: ./app
    volumes:
      - ./app:/home/app
    depends_on:
      - mysql
    networks:
      - rede-externa
      - rede-interna

  nginx:
    build: ./nginx
    ports:
        - 8000:80
        - 8080:80
    depends_on:
        - web
    networks:
      - rede-externa

networks:
  rede-externa:
    driver: bridge
  rede-interna:
    driver: bridge
